### ISSUE TITLE
bug: Kimi (Moonshot) auth fails with "deps.initializeAccounts is not a function" after recent update

### ISSUE THREAD

**Issue by king76** [kaitranntt/ccs#944]
### Affected area

Provider integration

### What broke?

Kimi (Moonshot) auth readiness check fails at startup with the error `deps.initializeAccounts is not a function`. As a result, CCS cannot verify the Kimi provider and falls back to native Read mode for the session. This may have been introduced by a recent CLIProxy or CCS update.

### Reproduction steps

1. Have CCS configured with Kimi (Moonshot) as a provider.
2. Start CCS (e.g. run `ccs kimi -c` in the terminal).
3. Observe the startup logs.

### Expected behavior

CCS starts normally, Kimi (Moonshot) auth is verified successfully, and the session uses the configured authentication method (not native Read fallback).

### Actual behavior

CCS fails to verify Kimi (Moonshot) auth readiness and prints:
`[i] CCS could not verify Kimi (Moonshot) auth readiness: deps.initializeAccounts is not a function`
The session falls back to native Read mode instead of using the configured auth. About 5 seconds later, the CLI process is forcefully terminated and the word "killed" appears in the terminal.

### CCS version

The last version

### Operating system

Linux

### Logs, screenshots, or terminal output

```shell
[|] Preparing CLIProxy... (0.1s)
[i] CLIProxy Plus update: v6.9.17-0 -> v6.9.22-0
[i] Run "ccs cliproxy stop" then restart to apply update
[OK] CLIProxy binary ready (0.2s)
[i] Using existing CLIProxy on port 8317 (session tracking unavailable)
[i] CCS could not verify Kimi (Moonshot) auth readiness: deps.initializeAccounts is not a function This session will use native Read.
[i] Thinking: auto (config: auto)
```

### Before submitting

- [ ] I searched existing issues first.
- [ ] I removed secrets and private data from logs/screenshots.
- [ ] I can still reproduce this on the latest released or dev build.

**Comment by king76** [comment]
Hi,

Same error after updating to 7.67.0-dev.6

thanks
